#!/bin/bash

usage()
{
  echo "$0 -u user -d domain"
  exit 1
}

while getopts u:d: OPT
do
	case $OPT in
	"u" ) AMAN="$OPTARG" ;;
	"d" ) DOMA="$OPTARG" ;;
	* ) usage ;;
	esac
done

if [ -z $AMAN ] || [ -z $DOMA ] ; then
 usage
fi
base_url="swift://vod/backup"
credential_file=/root/dup_swift
source $credential_file
duplicity collection-status $base_url/$AMAN/$DOMA | awk '
/Number of contained backup/ {print;}
/Full/ {
print $1"		"$6"/"$3"/"$4" "$5
}
/Incremental/ {
print $1"	"$6"/"$3"/"$4" "$5
}
'
