#!/bin/bash
credential=/usr/src/credential
source $credential
func_usage ()
{
  echo '##USAGE##'
  echo "  $0 -c ContainerName"
  exit 1
}

while getopts c: OPT
do
  case $OPT in
    "c" ) CNAME="$OPTARG" ;;
     * ) func_usage ;;
  esac
done

if [ -z ${CNAME} ]; then
  func_usage
fi

curl -s -X GET \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "X-Auth-Token: ${TOKEN}" \
${OBJ_URL}/${OBJ_PREFIX}${TENANT_ID}/${CNAME} |jq '.'

exit 0
