#!/bin/bash

function usage()
{
	echo " Remove php7-fpm configuration after deleting user"
	echo " Usage $0 -u user "
	exit 1
}
while getopts u: OPT
	do
		case $OPT in
		  "u" ) USERNAME="$OPTARG" ;;
		  "*" ) usage ;;
		esac
	done
if [ -z ${USERNAME} ]; then
	usage
fi

GetP=`cat /usr/src/.lifesafty_cPanel | head -c 24`
RET=`systemctl is-active php7-fpm.$USERNAME | grep active 2>&1 > /dev/null;echo $?`
if [ $RET -eq 0 ]; then
	systemctl stop php7-fpm.$USERNAME
	systemctl disable php7-fpm.$USERNAME
	rm -f /etc/php7-fpm.d/conf.d/$USERNAME.conf
	rm -f /etc/php7-fpm.d/www.$USERNAME.conf
	rm -f /usr/lib/systemd/system/php7-fpm.$USERNAME.service
elif [ -f "/usr/lib/systemd/system/php7-fpm.$USERNAME.service" ]; then
    systemctl disable php7-fpm.$USERNAME
	rm -f /etc/php7-fpm.d/conf.d/$USERNAME.conf
    rm -f /etc/php7-fpm.d/www.$USERNAME.conf
    rm -f /usr/lib/systemd/system/php7-fpm.$USERNAME.service
fi

systemctl daemon-reload
#Delete user from account table
mysql -p$GetP kusanagi -e "DELETE FROM account WHERE login_id = '"$USERNAME"'"
#Delete_provision
/usr/src/remove_all_provision -u $USERNAME
#Delete Filerun
sed -i "/'$USERNAME'/d" /etc/cron.daily/clean-Filerun
mysql -p$GetP -e "DROP DATABASE IF EXISTS Filerun_"$USERNAME"_db"
mysql -p$GetP -e "DROP USER 'Filerun_"$USERNAME"_user'@'%'"

groupdel $USERNAME
userdel --remove $USERNAME
DEL="sed -i '/$USERNAME:/d' /tmp/userpass_list.log"
echo $DEL | bash
rm -rf /var/log/$USERNAME
