#!/bin/bash

list_prov()
{
local i=0
cat /etc/kusanagi.d/profile.conf | awk -F / '/home\/'$1'/ {print $4}' | cut -d '"' -f1 | \
while read prov; do
   echo $((++i))". "$prov
   kusanagi remove -y $prov
   mysql -p$pwrd kusanagi -e "DELETE FROM provision WHERE provision_name='$prov'"
done
}
pwrd=`cat /usr/src/.lifesafty_cPanel | head -c 24`
list_prov $1
