#!/bin/bash

cd /etc/hhvm/conf.d

func_usage ()
{
  echo " Create HHVM configuration ini file for specific provision"
  echo " Usage : $0 -d domain -u user "
  exit 1
}

while getopts d:u: OPT
  do
    case $OPT in
	 "d" ) PROV="$OPTARG" ;;
	 "u" ) AMAN="$OPTARG" ;;
	 * ) func_usage ;;
	esac
  done

if [ -z ${PROV} ] || [ -z ${AMAN} ]; then
  func_usage
fi

## Create file configuration .ini
sed -e 's/%%DOMAIN%%/'$PROV'/' -e 's/%%USER%%/'$AMAN'/' template.ini > $PROV.ini
## Create new service
sed -e 's/%%DOMAIN%%/'$PROV'/' /etc/systemd/system/hhvm.service.template > /etc/systemd/system/hhvm.$PROV.service
## Start HHVM instance
systemctl daemon-reload
systemctl start hhvm.$PROV
systemctl enable hhvm.$PROV


