# Generated by Django 2.2 on 2020-03-16 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('backup_type', models.SmallIntegerField(default=0)),
                ('message', models.TextField(default='None')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteManager.Provision')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
