# Generated by Django 2.2 on 2020-04-01 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='None', max_length=200)),
                ('ip', models.CharField(default='None', max_length=20)),
                ('username', models.CharField(default='None', max_length=20)),
                ('provision_name', models.CharField(default='None', max_length=24)),
                ('app_id', models.SmallIntegerField(default=0)),
                ('db_name', models.CharField(max_length=50)),
                ('db_user', models.CharField(max_length=50)),
                ('db_password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('deactive_flg', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSys.Account')),
            ],
            options={
                'db_table': 'prosivions',
            },
        ),
    ]
