# Generated by Django 2.2 on 2020-04-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provision',
            table='provisions',
        ),
    ]
